PWD=$PWD
GISDATA="$PWD/gisdata"
TMPDIR="${GISDATA}/temp/"
UNZIPTOOL=unzip
WGETTOOL="/usr/bin/wget"

export PGBIN=/usr/lib/postgresql/10/bin
export PGPORT=5432
export PGHOST=0.0.0.0
export PGUSER=postgres
export PGPASSWORD=password
export PGDATABASE=postgres
PSQL="psql -p ${PGPORT} -h ${PGHOST} -U ${PGUSER} -d ${PGDATABASE}"
SHP2PGSQL=shp2pgsql
mkdir -p ${TMPDIR}     

ABBR=WA
FIPS=0
case $ABBR in
"AL")  FIPS=01;;
"AK")  FIPS=02;;
"AS")  FIPS=60;;
"AZ")  FIPS=04;;
"AR")  FIPS=05;;
"CA")  FIPS=06;;
"CO")  FIPS=08;;
"CT")  FIPS=09;;
"DE")  FIPS=10;;
"DC")  FIPS=11;;
"FL")  FIPS=12;;
"FM")  FIPS=64;;
"GA")  FIPS=13;;
"GU")  FIPS=66;;
"HI")  FIPS=15;;
"ID")  FIPS=16;;
"IL")  FIPS=17;;
"IN")  FIPS=18;;
"IA")  FIPS=19;;
"KS")  FIPS=20;;
"KY")  FIPS=21;;
"LA")  FIPS=22;;
"ME")  FIPS=23;;
"MH")  FIPS=68;;
"MD")  FIPS=24;;
"MA")  FIPS=25;;
"MI")  FIPS=26;;
"MN")  FIPS=27;;
"MS")  FIPS=28;;
"MO")  FIPS=29;;
"MT")  FIPS=30;;
"NE")  FIPS=31;;
"NV")  FIPS=32;;
"NH")  FIPS=33;;
"NJ")  FIPS=34;;
"NM")  FIPS=35;;
"NY")  FIPS=36;;
"NC")  FIPS=37;;
"ND")  FIPS=38;;
"MP")  FIPS=69;;
"OH")  FIPS=39;;
"OK")  FIPS=40;;
"OR")  FIPS=41;;
"PW")  FIPS=70;;
"PA")  FIPS=42;;
"PR")  FIPS=72;;
"RI")  FIPS=44;;
"SC")  FIPS=45;;
"SD")  FIPS=46;;
"TN")  FIPS=47;;
"TX")  FIPS=48;;
"UM")  FIPS=74;;
"UT")  FIPS=49;;
"VT")  FIPS=50;;
"VA")  FIPS=51;;
"VI")  FIPS=78;;
"WA")  FIPS=53;;
"WV")  FIPS=54;;
"WI")  FIPS=55;;
"WY")  FIPS=56;;
esac                                                                                                                                                                                                                                                                                                                                                                                                                                                     

#############
# Place
#############                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                       
wget https://www2.census.gov/geo/tiger/TIGER2017/PLACE/tl_2017_${FIPS}_place.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                     
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/PLACE                                                                                                                                                                                                                                                                                                                                                                                                                       
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_place.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                  
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_place(CONSTRAINT pk_${ABBR}_place PRIMARY KEY (plcidfp) ) INHERITS(tiger.place);"                                                                                                                                                                                                                                                                                                                                               
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_place.dbf tiger_staging.wa_place | ${PSQL}                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_place RENAME geoid TO plcidfp;SELECT loader_load_staged_data(lower('${ABBR}_place'), lower('${ABBR}_place')); ALTER TABLE tiger_data.${ABBR}_place ADD CONSTRAINT uidx_${ABBR}_place_gid UNIQUE (gid);"                                                                                                                                                                                                                       
${PSQL} -c "CREATE INDEX idx_${ABBR}_place_soundex_name ON tiger_data.${ABBR}_place USING btree (soundex(name));"                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_place_the_geom_gist ON tiger_data.${ABBR}_place USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_place ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"

#############
# Cousub
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wget https://www2.census.gov/geo/tiger/TIGER2017/COUSUB/tl_2017_${FIPS}_cousub.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                   
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/COUSUB                                                                                                                                                                                                                                                                                                                                                                                                                      
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_cousub.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                 
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_cousub(CONSTRAINT pk_${ABBR}_cousub PRIMARY KEY (cosbidfp), CONSTRAINT uidx_${ABBR}_cousub_gid UNIQUE (gid)) INHERITS(tiger.cousub);"                                                                                                                                                                                                                                                                                           
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_cousub.dbf tiger_staging.wa_cousub | ${PSQL}                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_cousub RENAME geoid TO cosbidfp;SELECT loader_load_staged_data(lower('${ABBR}_cousub'), lower('${ABBR}_cousub')); ALTER TABLE tiger_data.${ABBR}_cousub ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                              
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_cousub_the_geom_gist ON tiger_data.${ABBR}_cousub USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                        
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_cousub_countyfp ON tiger_data.${ABBR}_cousub USING btree(countyfp);"      

#############
# Tract
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wget https://www2.census.gov/geo/tiger/TIGER2017/TRACT/tl_2017_${FIPS}_tract.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                     
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/TRACT                                                                                                                                                                                                                                                                                                                                                                                                                       
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_tract.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                  
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_tract(CONSTRAINT pk_${ABBR}_tract PRIMARY KEY (tract_id) ) INHERITS(tiger.tract); "                                                                                                                                                                                                                                                                                                                                             
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_tract.dbf tiger_staging.wa_tract | ${PSQL}                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_tract RENAME geoid TO tract_id;  SELECT loader_load_staged_data(lower('${ABBR}_tract'), lower('${ABBR}_tract')); "                                                                                                                                                                                                                                                                                                            
        ${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_tract_the_geom_gist ON tiger_data.${ABBR}_tract USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                  
        ${PSQL} -c "VACUUM ANALYZE tiger_data.${ABBR}_tract;"                                                                                                                                                                                                                                                                                                                                                                                                               
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_tract ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"   

#############
# Faces
#############                                                                                                                                                                                                                                                                                                                                                           
cd $GISDATA       
wget -r --spider --no-parent https://www2.census.gov/geo/tiger/TIGER2017/FACES                                                                                                                                                                                                                                                                                                                                                                                                                                                    
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/FACES/                                                                                                                                                                                                                                                                                                                                                                                                                      
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_faces*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                    
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_faces(CONSTRAINT pk_${ABBR}_faces PRIMARY KEY (gid)) INHERITS(tiger.faces);"                                                                                                                                                                                                                                                                                                                                                    
for z in *faces*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                    
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_faces | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_faces'), lower('${ABBR}_faces'));"                                                                                                                                                                                                                                                                                                                                                                                
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_faces_the_geom_gist ON tiger_data.${ABBR}_faces USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_faces_tfid ON tiger_data.${ABBR}_faces USING btree (tfid);"                                                                                                                                                                                                                                                                                                                                                         
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_faces_countyfp ON tiger_data.${ABBR}_faces USING btree (countyfp);"                                                                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_faces ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
        ${PSQL} -c "vacuum analyze tiger_data.${ABBR}_faces;"                       

#############
# FeatNames
#############                                                                                                                                                                                                                                                                                                                                                                                           
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/FEATNAMES/                                                                                                                                                                                                                                                                                                                                                                                                                  
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_featnames*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_featnames(CONSTRAINT pk_${ABBR}_featnames PRIMARY KEY (gid)) INHERITS(tiger.featnames);ALTER TABLE tiger_data.${ABBR}_featnames ALTER COLUMN statefp SET DEFAULT '${FIPS}';"                                                                                                                                                                                                                                                    
for z in *featnames*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_featnames | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_featnames'), lower('${ABBR}_featnames'));"                                                                                                                                                                                                                                                                                                                                                                        
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_snd_name ON tiger_data.${ABBR}_featnames USING btree (soundex(name));"                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_lname ON tiger_data.${ABBR}_featnames USING btree (lower(name));"                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_tlid_statefp ON tiger_data.${ABBR}_featnames USING btree (tlid,statefp);"                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_featnames ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_featnames;"    

#############
# Edges
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/EDGES/                                                                                                                                                                                                                                                                                                                                                                                                                      
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_edges*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                    
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_edges(CONSTRAINT pk_${ABBR}_edges PRIMARY KEY (gid)) INHERITS(tiger.edges);"                                                                                                                                                                                                                                                                                                                                                    
for z in *edges*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                    
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_edges | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_edges'), lower('${ABBR}_edges'));"                                                                                                                                                                                                                                                                                                                                                                                
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_edges ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_tlid ON tiger_data.${ABBR}_edges USING btree (tlid);"                                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edgestfidr ON tiger_data.${ABBR}_edges USING btree (tfidr);"                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_tfidl ON tiger_data.${ABBR}_edges USING btree (tfidl);"                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_countyfp ON tiger_data.${ABBR}_edges USING btree (countyfp);"                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_edges_the_geom_gist ON tiger_data.${ABBR}_edges USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_zipl ON tiger_data.${ABBR}_edges USING btree (zipl);"                                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_state_loc(CONSTRAINT pk_${ABBR}_zip_state_loc PRIMARY KEY(zip,stusps,place)) INHERITS(tiger.zip_state_loc);"                                                                                                                                                                                                                                                                                                                
${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_state_loc(zip,stusps,statefp,place) SELECT DISTINCT e.zipl, '${ABBR}', '${FIPS}', p.name FROM tiger_data.${ABBR}_edges AS e INNER JOIN tiger_data.${ABBR}_faces AS f ON (e.tfidl = f.tfid OR e.tfidr = f.tfid) INNER JOIN tiger_data.${ABBR}_place As p ON(f.statefp = p.statefp AND f.placefp = p.placefp ) WHERE e.zipl IS NOT NULL;"                                                                                      
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_zip_state_loc_place ON tiger_data.${ABBR}_zip_state_loc USING btree(soundex(place));"                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_state_loc ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_edges;"                                                                                                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_zip_state_loc;"                                                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_lookup_base(CONSTRAINT pk_${ABBR}_zip_state_loc_city PRIMARY KEY(zip,state, county, city, statefp)) INHERITS(tiger.zip_lookup_base);"                                                                                                                                                                                                                                                                                       
${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_lookup_base(zip,state,county,city, statefp) SELECT DISTINCT e.zipl, '${ABBR}', c.name,p.name,'${FIPS}'  FROM tiger_data.${ABBR}_edges AS e INNER JOIN tiger.county As c  ON (e.countyfp = c.countyfp AND e.statefp = c.statefp AND e.statefp = '${FIPS}') INNER JOIN tiger_data.${ABBR}_faces AS f ON (e.tfidl = f.tfid OR e.tfidr = f.tfid) INNER JOIN tiger_data.${ABBR}_place As p ON(f.statefp = p.statefp AND f.placefp = p.placefp ) WHERE e.zipl IS NOT NULL;"
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_lookup_base ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_zip_lookup_base_citysnd ON tiger_data.${ABBR}_zip_lookup_base USING btree(soundex(city));"  

#############
# Addr
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/ADDR/                                                                                                                                                                                                                                                                                                                                                                                                                           
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                       
for z in tl_*_${FIPS}*_addr*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                         
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_addr(CONSTRAINT pk_${ABBR}_addr PRIMARY KEY (gid)) INHERITS(tiger.addr);ALTER TABLE tiger_data.${ABBR}_addr ALTER COLUMN statefp SET DEFAULT '${FIPS}';"                                                                                                                                                                                                                                                                            
for z in *addr*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_addr | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                                    
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_addr'), lower('${ABBR}_addr'));"                                                                                                                                                                                                                                                                                                                                                                                      
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_addr ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                                        
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_least_address ON tiger_data.${ABBR}_addr USING btree (least_hn(fromhn,tohn) );"                                                                                                                                                                                                                                                                                                                                    
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_tlid_statefp ON tiger_data.${ABBR}_addr USING btree (tlid, statefp);"                                                                                                                                                                                                                                                                                                                                              
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_zip ON tiger_data.${ABBR}_addr USING btree (zip);"                                                                                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_state(CONSTRAINT pk_${ABBR}_zip_state PRIMARY KEY(zip,stusps)) INHERITS(tiger.zip_state); "                                                                                                                                                                                                                                                                                                                             
        ${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_state(zip,stusps,statefp) SELECT DISTINCT zip, '${ABBR}', '${FIPS}' FROM tiger_data.${ABBR}_addr WHERE zip is not null;"                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_state ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
        ${PSQL} -c "vacuum analyze tiger_data.${ABBR}_addr;"

