PWD=$PWD
GISDATA="$PWD/gisdata"
TMPDIR="${GISDATA}/temp/"
UNZIPTOOL=unzip
WGETTOOL="/usr/bin/wget"
BASEURL="https://www2.census.gov/geo/tiger/TIGER2017"

export PGBIN=/usr/lib/postgresql/10/bin
export PGPORT=5432
export PGHOST=0.0.0.0
export PGUSER=postgres
export PGPASSWORD=password
export PGDATABASE=postgres
PSQL="psql -p ${PGPORT} -h ${PGHOST} -U ${PGUSER} -d ${PGDATABASE}"
SHP2PGSQL=shp2pgsql
mkdir -p ${TMPDIR}     

get_fips_from_abbr () {
    local abbr=$1
    local fips=0
    case $abbr in
        "AL")  fips=01;;
        "AK")  fips=02;;
        "AS")  fips=60;;
        "AZ")  fips=04;;
        "AR")  fips=05;;
        "CA")  fips=06;;
        "CO")  fips=08;;
        "CT")  fips=09;;
        "DE")  fips=10;;
        "DC")  fips=11;;
        "FL")  fips=12;;
        "FM")  fips=64;;
        "GA")  fips=13;;
        "GU")  fips=66;;
        "HI")  fips=15;;
        "ID")  fips=16;;
        "IL")  fips=17;;
        "IN")  fips=18;;
        "IA")  fips=19;;
        "KS")  fips=20;;
        "KY")  fips=21;;
        "LA")  fips=22;;
        "ME")  fips=23;;
        "MH")  fips=68;;
        "MD")  fips=24;;
        "MA")  fips=25;;
        "MI")  fips=26;;
        "MN")  fips=27;;
        "MS")  fips=28;;
        "MO")  fips=29;;
        "MT")  fips=30;;
        "NE")  fips=31;;
        "NV")  fips=32;;
        "NH")  fips=33;;
        "NJ")  fips=34;;
        "NM")  fips=35;;
        "NY")  fips=36;;
        "NC")  fips=37;;
        "ND")  fips=38;;
        "MP")  fips=69;;
        "OH")  fips=39;;
        "OK")  fips=40;;
        "OR")  fips=41;;
        "PW")  fips=70;;
        "PA")  fips=42;;
        "PR")  fips=72;;
        "RI")  fips=44;;
        "SC")  fips=45;;
        "SD")  fips=46;;
        "TN")  fips=47;;
        "TX")  fips=48;;
        "UM")  fips=74;;
        "UT")  fips=49;;
        "VT")  fips=50;;
        "VA")  fips=51;;
        "VI")  fips=78;;
        "WA")  fips=53;;
        "WV")  fips=54;;
        "WI")  fips=55;;
        "WY")  fips=56;;
    esac
    echo $fips
}

get_fips_files () {
    local url=$1
    local fips=$2
    local files=($(wget -O - $url \
        | perl -nle 'print if m{(?=\"tl)(.*?)(?<=>)}g' \
        | perl -nle 'print m{(?=\"tl)(.*?)(?<=>)}g' \
        | sed -e 's/[\">]//g'))
    local matched=($(echo "${files[*]}" | tr ' ' '\n' | grep "tl_2017_$fips"))
    echo "${matched[*]}"
}

ABBR='WA'
FIPS=$(get_fips_from_abbr $ABBR)
if [ $FIPS -eq 0 ]; then
    echo "Error: $ABBR is not a recognized US state abbreviation"
    exit 125
fi

#############
# Place
#############                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                       
wget $BASEURL/PLACE/tl_2017_${FIPS}_place.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                     
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/PLACE                                                                                                                                                                                                                                                                                                                                                                                                                       
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_place.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                  
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_place(CONSTRAINT pk_${ABBR}_place PRIMARY KEY (plcidfp) ) INHERITS(tiger.place);"                                                                                                                                                                                                                                                                                                                                               
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_place.dbf tiger_staging.wa_place | ${PSQL}                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_place RENAME geoid TO plcidfp;SELECT loader_load_staged_data(lower('${ABBR}_place'), lower('${ABBR}_place')); ALTER TABLE tiger_data.${ABBR}_place ADD CONSTRAINT uidx_${ABBR}_place_gid UNIQUE (gid);"                                                                                                                                                                                                                       
${PSQL} -c "CREATE INDEX idx_${ABBR}_place_soundex_name ON tiger_data.${ABBR}_place USING btree (soundex(name));"                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_place_the_geom_gist ON tiger_data.${ABBR}_place USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_place ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"

#############
# Cousub
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wget $BASEURL/COUSUB/tl_2017_${FIPS}_cousub.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                   
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/COUSUB                                                                                                                                                                                                                                                                                                                                                                                                                      
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_cousub.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                 
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_cousub(CONSTRAINT pk_${ABBR}_cousub PRIMARY KEY (cosbidfp), CONSTRAINT uidx_${ABBR}_cousub_gid UNIQUE (gid)) INHERITS(tiger.cousub);"                                                                                                                                                                                                                                                                                           
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_cousub.dbf tiger_staging.wa_cousub | ${PSQL}                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_cousub RENAME geoid TO cosbidfp;SELECT loader_load_staged_data(lower('${ABBR}_cousub'), lower('${ABBR}_cousub')); ALTER TABLE tiger_data.${ABBR}_cousub ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                              
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_cousub_the_geom_gist ON tiger_data.${ABBR}_cousub USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                        
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_cousub_countyfp ON tiger_data.${ABBR}_cousub USING btree(countyfp);"      

#############
# Tract
#############   
cd $GISDATA                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
wget $BASEURL/TRACT/tl_2017_${FIPS}_tract.zip --mirror --reject=html                                                                                                                                                                                                                                                                                                                                                                     
cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/TRACT                                                                                                                                                                                                                                                                                                                                                                                                                       
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_2017_${FIPS}*_tract.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                  
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_tract(CONSTRAINT pk_${ABBR}_tract PRIMARY KEY (tract_id) ) INHERITS(tiger.tract); "                                                                                                                                                                                                                                                                                                                                             
${SHP2PGSQL} -D -c -s 4269 -g the_geom   -W "latin1" tl_2017_${FIPS}_tract.dbf tiger_staging.wa_tract | ${PSQL}                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "ALTER TABLE tiger_staging.${ABBR}_tract RENAME geoid TO tract_id;  SELECT loader_load_staged_data(lower('${ABBR}_tract'), lower('${ABBR}_tract')); "                                                                                                                                                                                                                                                                                                            
        ${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_tract_the_geom_gist ON tiger_data.${ABBR}_tract USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                  
        ${PSQL} -c "VACUUM ANALYZE tiger_data.${ABBR}_tract;"                                                                                                                                                                                                                                                                                                                                                                                                               
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_tract ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"   

#############
# Faces
#############                                                                                                                                                                                                                                                                                                                                                           
cd $GISDATA
files=($(get_fips_files $BASEURL/FACES $FIPS))

for i in "${files[@]}"
do
	wget --mirror $BASEURL/FACES/$i
done

cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/FACES/                                                                                                                                                                                                                                                                                                                                                                                                                      
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_faces*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                    
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_faces(CONSTRAINT pk_${ABBR}_faces PRIMARY KEY (gid)) INHERITS(tiger.faces);"                                                                                                                                                                                                                                                                                                                                                    
for z in *faces*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                    
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_faces | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_faces'), lower('${ABBR}_faces'));"                                                                                                                                                                                                                                                                                                                                                                                
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_faces_the_geom_gist ON tiger_data.${ABBR}_faces USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_faces_tfid ON tiger_data.${ABBR}_faces USING btree (tfid);"                                                                                                                                                                                                                                                                                                                                                         
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_faces_countyfp ON tiger_data.${ABBR}_faces USING btree (countyfp);"                                                                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_faces ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
        ${PSQL} -c "vacuum analyze tiger_data.${ABBR}_faces;"                       

#############
# FeatNames
#############                                                                                                                                                                                                                                                                                                                                                                                           
cd $GISDATA
files=($(get_fips_files $BASEURL/FEATNAMES $FIPS))

for i in "${files[@]}"
do
	wget --mirror $BASEURL/FEATNAMES/$i
done

cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/FEATNAMES/
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_featnames*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_featnames(CONSTRAINT pk_${ABBR}_featnames PRIMARY KEY (gid)) INHERITS(tiger.featnames);ALTER TABLE tiger_data.${ABBR}_featnames ALTER COLUMN statefp SET DEFAULT '${FIPS}';"                                                                                                                                                                                                                                                    
for z in *featnames*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_featnames | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_featnames'), lower('${ABBR}_featnames'));"                                                                                                                                                                                                                                                                                                                                                                        
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_snd_name ON tiger_data.${ABBR}_featnames USING btree (soundex(name));"                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_lname ON tiger_data.${ABBR}_featnames USING btree (lower(name));"                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_featnames_tlid_statefp ON tiger_data.${ABBR}_featnames USING btree (tlid,statefp);"                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_featnames ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_featnames;"    

#############
# Edges
#############   
cd $gisdata
files=($(get_fips_files $BASEURL/EDGES $FIPS))

for i in "${files[@]}"
do
	wget --mirror $BASEURL/EDGES/$i
done

cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/EDGES/
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                   
for z in tl_*_${FIPS}*_edges*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                    
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_edges(CONSTRAINT pk_${ABBR}_edges PRIMARY KEY (gid)) INHERITS(tiger.edges);"                                                                                                                                                                                                                                                                                                                                                    
for z in *edges*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                    
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_edges | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_edges'), lower('${ABBR}_edges'));"                                                                                                                                                                                                                                                                                                                                                                                
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_edges ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                                   
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_tlid ON tiger_data.${ABBR}_edges USING btree (tlid);"                                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edgestfidr ON tiger_data.${ABBR}_edges USING btree (tfidr);"                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_tfidl ON tiger_data.${ABBR}_edges USING btree (tfidl);"                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_countyfp ON tiger_data.${ABBR}_edges USING btree (countyfp);"                                                                                                                                                                                                                                                                                                                                                         
${PSQL} -c "CREATE INDEX tiger_data_${ABBR}_edges_the_geom_gist ON tiger_data.${ABBR}_edges USING gist(the_geom);"                                                                                                                                                                                                                                                                                                                                                          
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_edges_zipl ON tiger_data.${ABBR}_edges USING btree (zipl);"                                                                                                                                                                                                                                                                                                                                                                 
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_state_loc(CONSTRAINT pk_${ABBR}_zip_state_loc PRIMARY KEY(zip,stusps,place)) INHERITS(tiger.zip_state_loc);"                                                                                                                                                                                                                                                                                                                
${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_state_loc(zip,stusps,statefp,place) SELECT DISTINCT e.zipl, '${ABBR}', '${FIPS}', p.name FROM tiger_data.${ABBR}_edges AS e INNER JOIN tiger_data.${ABBR}_faces AS f ON (e.tfidl = f.tfid OR e.tfidr = f.tfid) INNER JOIN tiger_data.${ABBR}_place As p ON(f.statefp = p.statefp AND f.placefp = p.placefp ) WHERE e.zipl IS NOT NULL;"                                                                                      
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_zip_state_loc_place ON tiger_data.${ABBR}_zip_state_loc USING btree(soundex(place));"                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_state_loc ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_edges;"                                                                                                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "vacuum analyze tiger_data.${ABBR}_zip_state_loc;"                                                                                                                                                                                                                                                                                                                                                                                                               
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_lookup_base(CONSTRAINT pk_${ABBR}_zip_state_loc_city PRIMARY KEY(zip,state, county, city, statefp)) INHERITS(tiger.zip_lookup_base);"                                                                                                                                                                                                                                                                                       
${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_lookup_base(zip,state,county,city, statefp) SELECT DISTINCT e.zipl, '${ABBR}', c.name,p.name,'${FIPS}'  FROM tiger_data.${ABBR}_edges AS e INNER JOIN tiger.county As c  ON (e.countyfp = c.countyfp AND e.statefp = c.statefp AND e.statefp = '${FIPS}') INNER JOIN tiger_data.${ABBR}_faces AS f ON (e.tfidl = f.tfid OR e.tfidr = f.tfid) INNER JOIN tiger_data.${ABBR}_place As p ON(f.statefp = p.statefp AND f.placefp = p.placefp ) WHERE e.zipl IS NOT NULL;"
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_lookup_base ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_zip_lookup_base_citysnd ON tiger_data.${ABBR}_zip_lookup_base USING btree(soundex(city));"  

#############
# Addr
#############   
cd $GISDATA
files=($(get_fips_files $BASEURL/ADDR $FIPS))

for i in "${files[@]}"
do
	wget --mirror $BASEURL/ADDR/$i
done

cd $GISDATA/www2.census.gov/geo/tiger/TIGER2017/ADDR/
rm -f ${TMPDIR}/*.*                                                                                                                                                                                                                                                                                                                                                                                                                                                             
${PSQL} -c "DROP SCHEMA IF EXISTS tiger_staging CASCADE;"                                                                                                                                                                                                                                                                                                                                                                                                                       
${PSQL} -c "CREATE SCHEMA tiger_staging;"                                                                                                                                                                                                                                                                                                                                                                                                                                       
for z in tl_*_${FIPS}*_addr*.zip ; do $UNZIPTOOL -o -d $TMPDIR $z; done                                                                                                                                                                                                                                                                                                                                                                                                         
cd $TMPDIR;                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_addr(CONSTRAINT pk_${ABBR}_addr PRIMARY KEY (gid)) INHERITS(tiger.addr);ALTER TABLE tiger_data.${ABBR}_addr ALTER COLUMN statefp SET DEFAULT '${FIPS}';"                                                                                                                                                                                                                                                                            
for z in *addr*.dbf; do                                                                                                                                                                                                                                                                                                                                                                                                                                                         
${SHP2PGSQL} -D   -D -s 4269 -g the_geom -W "latin1" $z tiger_staging.${ABBR}_addr | ${PSQL}                                                                                                                                                                                                                                                                                                                                                                                    
${PSQL} -c "SELECT loader_load_staged_data(lower('${ABBR}_addr'), lower('${ABBR}_addr'));"                                                                                                                                                                                                                                                                                                                                                                                      
done                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_addr ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                                        
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_least_address ON tiger_data.${ABBR}_addr USING btree (least_hn(fromhn,tohn) );"                                                                                                                                                                                                                                                                                                                                    
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_tlid_statefp ON tiger_data.${ABBR}_addr USING btree (tlid, statefp);"                                                                                                                                                                                                                                                                                                                                              
        ${PSQL} -c "CREATE INDEX idx_tiger_data_${ABBR}_addr_zip ON tiger_data.${ABBR}_addr USING btree (zip);"                                                                                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "CREATE TABLE tiger_data.${ABBR}_zip_state(CONSTRAINT pk_${ABBR}_zip_state PRIMARY KEY(zip,stusps)) INHERITS(tiger.zip_state); "                                                                                                                                                                                                                                                                                                                             
        ${PSQL} -c "INSERT INTO tiger_data.${ABBR}_zip_state(zip,stusps,statefp) SELECT DISTINCT zip, '${ABBR}', '${FIPS}' FROM tiger_data.${ABBR}_addr WHERE zip is not null;"                                                                                                                                                                                                                                                                                                 
        ${PSQL} -c "ALTER TABLE tiger_data.${ABBR}_zip_state ADD CONSTRAINT chk_statefp CHECK (statefp = '${FIPS}');"                                                                                                                                                                                                                                                                                                                                                           
        ${PSQL} -c "vacuum analyze tiger_data.${ABBR}_addr;"

