# Generated by Django 2.2.4 on 2019-09-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=256)),
                ('street_number', models.CharField(max_length=16)),
                ('street_name', models.CharField(max_length=128)),
                ('street_type', models.CharField(max_length=32)),
                ('unit_number', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=16)),
                ('latlong_text', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
            ],
        ),
    ]
